// Generated by https://quicktype.io

export interface DashboarSummaryResponse {
    notPaidOrders:           number;
    numberOfOrder:           number;
    paidOrders:              number;
    numberOfCLients:         number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
}
